---
abstract: 'IOLoop interface to Proc::Background'
author:
  - 'Brian Medley <bpmedley@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-IOLoop-ProcBackground
requires:
  Mojolicious: 0
  Proc::Background: 0
version: 0.01
